const allStoresSalesReportTemplate = [
  {
    17: 'Movement Data',
  },
  { 17: '*', 65: 'Grand Total' },
  {
    17: '1 RALEIGH HILLS',
    19: '2 SELLWOOD',
    21: '3 ORENCO STATION',
    23: '4 CONCORDIA',
    25: '5 SEVEN CORNERS',
    27: '6 ARBOR LODGE',
    29: '7 MOUNTAIN PARK',
    31: '8 CEDAR HILLS CROSSING',
    33: '9 HAPPY VALLEY',
    35: '10 HAWTHORNE',
    37: '11 PROGRESS RIDGE',
    39: '12 FISHERS LANDING',
    41: '13 WILLIAMS',
    43: '14 NYBERG RIVERS',
    45: '15 GRANT PARK',
    47: '16 SLABTOWN',
    49: '17 WOODSTOCK',
    51: '18 UNIVERSITY PARK',
    53: '1201 WESTSIDE NLCM',
    55: '1202 CAPITOLA NLCM',
    57: '1203 PACIFIC NLCM',
    59: '1204 HALF MOON BAY NLCM',
    61: '1205 EVERGREEN NSM',
    63: '1209 APTOS NLCM',
  },
  {
    0: 'Brand Name',
    1: 'Description',
    2: 'UPC',
    3: 'Size',
    4: 'Pack',
    5: 'Report Rank',
    6: 'Current Cost',
    7: 'Current Reg Retail',
    8: 'Current Retail',
    9: 'CurrentCaseCost',
    10: 'Minor Catg Name',
    11: 'Organic',
    12: 'Vendor Name',
    13: 'UPC w/Check Digit',
    14: 'Price Link',
    15: 'Price Link Name',
    16: 'Major Catg Name',
    17: 'Total Movement',
    18: 'Sales $',
    19: 'Total Movement',
    20: 'Sales $',
    21: 'Total Movement',
    22: 'Sales $',
    23: 'Total Movement',
    24: 'Sales $',
    25: 'Total Movement',
    26: 'Sales $',
    27: 'Total Movement',
    28: 'Sales $',
    29: 'Total Movement',
    30: 'Sales $',
    31: 'Total Movement',
    32: 'Sales $',
    33: 'Total Movement',
    34: 'Sales $',
    35: 'Total Movement',
    36: 'Sales $',
    37: 'Total Movement',
    38: 'Sales $',
    39: 'Total Movement',
    40: 'Sales $',
    41: 'Total Movement',
    42: 'Sales $',
    43: 'Total Movement',
    44: 'Sales $',
    45: 'Total Movement',
    46: 'Sales $',
    47: 'Total Movement',
    48: 'Sales $',
    49: 'Total Movement',
    50: 'Sales $',
    51: 'Total Movement',
    52: 'Sales $',
    53: 'Total Movement',
    54: 'Sales $',
    55: 'Total Movement',
    56: 'Sales $',
    57: 'Total Movement',
    58: 'Sales $',
    59: 'Total Movement',
    60: 'Sales $',
    61: 'Total Movement',
    62: 'Sales $',
    63: 'Total Movement',
    64: 'Sales $',
    65: 'Total Movement',
    66: 'Sales $',
  },
  {
    0: 'Store Number: CMPNY (Company Totals) ',
  },
];

export default allStoresSalesReportTemplate;
