const allStoresSalesReportTemplate = [
  {
    0: '',
    2: '',
    16: 'Movement Data',
  },
  { 16: '*', 64: 'Grand Total' },
  {
    16: '1 RALEIGH HILLS',
    18: '2 SELLWOOD',
    20: '3 ORENCO STATION',
    22: '4 CONCORDIA',
    24: '5 SEVEN CORNERS',
    26: '6 ARBOR LODGE',
    28: '7 MOUNTAIN PARK',
    30: '8 CEDAR HILLS CROSSING',
    32: '9 HAPPY VALLEY',
    34: '10 HAWTHORNE',
    36: '11 PROGRESS RIDGE',
    38: '12 FISHERS LANDING',
    40: '13 WILLIAMS',
    42: '14 NYBERG RIVERS',
    44: '15 GRANT PARK',
    46: '16 SLABTOWN',
    48: '17 WOODSTOCK',
    50: '18 UNIVERSITY PARK',
    52: '1201 WESTSIDE NLCM',
    54: '1202 CAPITOLA NLCM',
    56: '1203 PACIFIC NLCM',
    58: '1204 HALF MOON BAY NLCM',
    60: '1205 EVERGREEN NSM',
    62: '1209 APTOS NLCM',
  },
  {
    0: 'Brand Name',
    1: 'Description',
    2: 'UPC',
    3: 'Size',
    4: 'Pack',
    5: 'Report Rank',
    6: 'Current Cost',
    7: 'Current Reg Retail',
    8: 'Current Retail',
    9: 'CurrentCaseCost',
    10: 'Minor Catg Name',
    11: 'Organic',
    12: 'Vendor Name',
    13: 'UPC w/Check Digit',
    14: 'Price Link',
    15: 'Price Link Name',
    16: 'Total Movement',
    17: 'Sales $',
    18: 'Total Movement',
    19: 'Sales $',
    20: 'Total Movement',
    21: 'Sales $',
    22: 'Total Movement',
    23: 'Sales $',
    24: 'Total Movement',
    25: 'Sales $',
    26: 'Total Movement',
    27: 'Sales $',
    28: 'Total Movement',
    29: 'Sales $',
    30: 'Total Movement',
    31: 'Sales $',
    32: 'Total Movement',
    33: 'Sales $',
    34: 'Total Movement',
    35: 'Sales $',
    36: 'Total Movement',
    37: 'Sales $',
    38: 'Total Movement',
    39: 'Sales $',
    40: 'Total Movement',
    41: 'Sales $',
    42: 'Total Movement',
    43: 'Sales $',
    44: 'Total Movement',
    45: 'Sales $',
    46: 'Total Movement',
    47: 'Sales $',
    48: 'Total Movement',
    49: 'Sales $',
    50: 'Total Movement',
    51: 'Sales $',
    52: 'Total Movement',
    53: 'Sales $',
    54: 'Total Movement',
    55: 'Sales $',
    56: 'Total Movement',
    57: 'Sales $',
    58: 'Total Movement',
    59: 'Sales $',
    60: 'Total Movement',
    61: 'Sales $',
    62: 'Total Movement',
    63: 'Sales $',
    64: 'Total Movement',
    65: 'Sales $',
  },
  {
    0: 'Store Number: CMPNY (Company Totals) ',
  },
];

export default allStoresSalesReportTemplate;
